[[redirects]]
  from = "/api/*"
  to = "https://www.chungbuk.go.kr/:splat"
  status = 200
  
[context.production.environment]
  REACT_APP_SERVICE_KEY = "8UBV6FlfDpcGEbHNMcoCqEfgBbeaCoAvTDkSnJwzQiR7Qg8tIWaej%2FFX%2BwJL%2BDfZ%2Bb56dXnz6IpuFBM3evA%2F1w%3D%3D"
