[[redirects]]
  from = "/api/*"
  to = "http://apis.data.go.kr/6430000/cbRecreationalForestInfoService/:splat"
  status = 200
  
[context.production.environment]
  SERVICE_KEY = "From netlify.toml"
  REACT_APP_SERVICE_KEY = "From netlify.toml (REACT_APP_)"
